logging.level.ROOT=INFO
# Input fixed-width file path
input.file=src/main/resources/sample.txt

# Temp file that will contain only the <details>...</details> part
details.temp.file=target/details.xml

# Final output file that includes header + details + footer
output.file=target/output.xml

# Let Spring Boot create an embedded H2 DataSource
spring.datasource.url=jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Initialize Spring Batch metadata tables
spring.batch.jdbc.initialize-schema=always

# Run the chunk-based job explicitly
spring.batch.job.enabled=false

order.input.file=src/main/resources/order.txt
order.output.file=target/order_output.xml

cron.parseToXmlChunkJob=*/10 * * * * *
cron.parseOrderToXmlJob=*/10 * * * * *
